In [43]:
import cv2
import numpy as np
import seaborn
from PIL import Image

In [20]:
import os

Esta linha de comando serve para pegar a biblioteca para que possamos listar os arquivos que iremos usar.

In [21]:
print(os.listdir("./New_DB/yalefaces/train/"))

['subject01.glasses.gif', 'subject01.leftlight.gif', 'subject01.noglasses.gif', 'subject01.normal.gif', 'subject01.rightlight.gif', 'subject01.sad.gif', 'subject01.sleepy.gif', 'subject01.surprised.gif', 'subject01.wink.gif', 'subject02.glasses.gif', 'subject02.happy.gif', 'subject02.noglasses.gif', 'subject02.normal.gif', 'subject02.rightlight.gif', 'subject02.sad.gif', 'subject02.sleepy.gif', 'subject02.surprised.gif', 'subject02.wink.gif', 'subject03.centerlight.gif', 'subject03.happy.gif', 'subject03.noglasses.gif', 'subject03.normal.gif', 'subject03.rightlight.gif', 'subject03.sad.gif', 'subject03.sleepy.gif', 'subject03.surprised.gif', 'subject03.wink.gif', 'subject04.centerlight.gif', 'subject04.glasses.gif', 'subject04.happy.gif', 'subject04.noglasses.gif', 'subject04.normal.gif', 'subject04.rightlight.gif', 'subject04.sad.gif', 'subject04.sleepy.gif', 'subject04.wink.gif', 'subject05.centerlight.gif', 'subject05.glasses.gif', 'subject05.happy.gif', 'subject05.leftlight.gif', '

In [22]:
def get_image_data():
    paths = [os.path.join('./New_DB/yalefaces/train/' , p)  for p in os.listdir("./New_DB/yalefaces/train/")]
    #for i in paths:
        #print(i)
    return paths

Função que pega todos os caminhos de onde estão as imagens de teste do algoritmo.
E farei retornar como strings para extrair esses caminhos.

In [23]:
caminhos = get_image_data()

Agora tenho todos os caminhos.

In [54]:
def get_imagem_escala_cinza(image):
    lista_imagens = []
    for path in image:
        #print(path)
        imagens = Image.open(path).convert('L')
        print(type(imagens))
        lista_imagens.append(imagens)
        
    return lista_imagens

Com a função acima fizemos a conversão dos caminhos em Imagens.
De imagens fizemos a conversão em escala de cinza, reduzindo a imagem para pre-processamento.

In [55]:
imagens_cinza = get_imagem_escala_cinza(caminhos)

<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.Image.Image'>
<class 'PIL.

In [60]:
def converte_imagens_np_Array(imagens):
    for im in imagens:
        image_np = np.array(im, 'uint8')
    print(image_np)

In [61]:
converte_imagens_np_Array(imagens_cinza)

[[130 130 130 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [ 68  68  68 ...  68  68  68]]
